""" This modules manages HTTP interaction with the Trello API."""

#import httplib2

class TrelloClient(object):

    """ Base class for Trello API access."""

    def __init__(self, api_key, token):
        """
        Constructor

        :api_key: API key generated at https://trello.com/1/appKey/generate
        :token: OAuth token generated by the user

        """

        self.api_key = api_key
        self.auth_token = token

    def build_url(self, path):
        """
        Builds a Trello URL.

        :path: URL path

        """

        url = 'https://api.trello.com/1%(path)s?key=%(key)s&token=%(token)s' % (
            {'path':path, 'key':self.api_key, 'token':self.auth_token})

        return url

